# Generated by Django 3.0.9 on 2020-09-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='group_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
