# Generated by Django 3.0.9 on 2020-09-29 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_usermodel_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(default=123456789, max_length=18, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='group_code',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Phone number format must be +99999999', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
