# Generated by Django 3.0.9 on 2020-11-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201117_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsGroup',
            new_name='StudentsGroupModel',
        ),
    ]
