# Generated by Django 3.0.9 on 2020-11-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201117_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsgroupmodel',
            options={'verbose_name': 'Группа студентов', 'verbose_name_plural': 'Группы студентов'},
        ),
        migrations.AddField(
            model_name='studentsgroupmodel',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
