# Generated by Django 3.0.9 on 2020-11-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201117_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsgroupmodel',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Обучение завершено'),
        ),
    ]
