# Generated by Django 3.1.4 on 2020-12-28 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20201223_1255'),
        ('profiles', '0008_auto_20201228_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsgroupmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='courses.course'),
        ),
    ]
