# Generated by Django 3.0.9 on 2020-12-02 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_studentcoursestatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentCourseStatus',
            new_name='StudentModuleTestStatus',
        ),
    ]
