# Generated by Django 3.0.9 on 2020-08-04 14:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
